### PR TITLE
Fix for origins-architectury #239

### PR DESCRIPTION
**Pull request by ChrysanthCow**
See [#239](https://github.com/EdwinMindcraft/origins-architectury/issues/239) of origins-architectury

### CODE REVIEW

**Comment by RaymondBlaze** [comment]
Maybe backport this to 1.18.2 while it's still active? :)

**Comment by EdwinMindcraft** [comment]
I am not actively working on 1.18.2 since switching workspaces is a pain (thank FG for the ~25 minutes of decomp), but if there are PRs, I'll do a pass at some point.
Also I'm still waiting on forge to fix JiJ for 1.18.2, but that's another kind of pain. I can just revert the buildscript anyways and release a non-jarjar'd version.

**Comment by RaymondBlaze** [comment]
I was just hoping if the fix could come out with any possible new release for 1.18.2.
Even if there won't be any new release for 1.18.2, that's fine for me, I'm not urgently needing the fix nor the template :)

**Comment by ChrysanthCow** [comment]
I'd be willing to port this to 1.18.2 once Forge fixes JiJ for that version but I'd like to know Edwin's entire stance on such a thing before I'd do it.

**Comment by EdwinMindcraft** [comment]
My official stance on 1.18.2 is "I don't have the time to do it".
My unofficial stance is "This is a nightmare, forge is busted, I need to backport every network change I introduced in 1.19 to have a half decent synchronization system, and make sure it's stable enough, but I don't have the mental capacity to do that right now".

Keeping 1.18.2 up to what I would consider a working standard is a lot of work that I just don't have the time to put in right now, but as stated previously, there will be another 1.18.2 if and when forge decides to fix JiJ.

Changes necessary are PR'd to both Forge and SJH, but unfortunately, we're talking about a non-mainline forge repository, so I expect changes to take *at least* a full month before cpw even takes notice of them.

**Pull request merged**
